package GUI;

import Controllers.*;
import Models.*;
import java.io.*;
import javax.swing.*;

public class GUI extends javax.swing.JFrame {

	/**
	 * Creates new form GUII
	 */
	public GUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        popupMenu1 = new java.awt.PopupMenu();
        jButton_FilePath = new javax.swing.JButton();
        jButton_Run = new javax.swing.JButton();
        jLabel_Target = new javax.swing.JLabel();
        jLabel_Replacement = new javax.swing.JLabel();
        jLabel_FilePath = new javax.swing.JLabel();
        jCheckBox_SubFolders = new javax.swing.JCheckBox();
        jCheckBox_isFiles = new javax.swing.JCheckBox();
        jCheckBox_isFolder = new javax.swing.JCheckBox();
        jTextField_Target = new javax.swing.JTextField();
        jTextField_Replace = new javax.swing.JTextField();
        jTextField_FilePath = new javax.swing.JTextField();
        jButton_Demo = new javax.swing.JButton();
        jLabel_Action = new javax.swing.JLabel();
        jButton_Undo = new javax.swing.JButton();
        jComboBox_Action = new javax.swing.JComboBox<>();

        jCheckBox1.setText("jCheckBox1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.white);

        jButton_FilePath.setText("Load");
        jButton_FilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FilePathActionPerformed(evt);
            }
        });

        jButton_Run.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Run.setText("Run");
        jButton_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RunActionPerformed(evt);
            }
        });

        jLabel_Target.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Target.setText("Target");

        jLabel_Replacement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Replacement.setText("Replacement");

        jLabel_FilePath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_FilePath.setText("File Path");

        jCheckBox_SubFolders.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_SubFolders.setText("Sub Folders");

        jCheckBox_isFiles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_isFiles.setSelected(true);
        jCheckBox_isFiles.setText("Files");

        jCheckBox_isFolder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_isFolder.setText("Folders");

        jTextField_Target.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Replace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_FilePath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_Demo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Demo.setText("Demo");
        jButton_Demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DemoActionPerformed(evt);
            }
        });

        jLabel_Action.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Action.setText("Action");

        jButton_Undo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Undo.setText("Undo");
        jButton_Undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UndoActionPerformed(evt);
            }
        });

        jComboBox_Action.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Action.setModel(new DefaultComboBoxModel(Actions.List.keySet().toArray()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox_SubFolders)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_isFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox_isFiles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(jButton_Undo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Demo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Run))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Target, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Replacement)
                            .addComponent(jLabel_Action, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Target)
                            .addComponent(jTextField_FilePath)
                            .addComponent(jTextField_Replace)
                            .addComponent(jComboBox_Action, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_FilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jButton_FilePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Target, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Target, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Replace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Replacement, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Action, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Demo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox_SubFolders)
                        .addComponent(jCheckBox_isFolder)
                        .addComponent(jCheckBox_isFiles))
                    .addComponent(jButton_Undo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void jButton_FilePathActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_FilePathActionPerformed
   {//GEN-HEADEREND:event_jButton_FilePathActionPerformed

	   JFileChooser browse = new JFileChooser();
	   browse.setDialogTitle("Browse");
	   browse.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
	   browse.setAcceptAllFileFilterUsed(false);
	   browse.setRequestFocusEnabled(rootPaneCheckingEnabled);
	   browse.setCurrentDirectory(new File("."));

	   if (browse.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
		   if (browse.getSelectedFile().toString() == null) {
			   JOptionPane.showMessageDialog(null, "can't load the path", "Error", JOptionPane.ERROR_MESSAGE);
		   } else {
			   jTextField_FilePath.setText(browse.getSelectedFile().toString());
		   }
	   }

   }//GEN-LAST:event_jButton_FilePathActionPerformed
    private void jButton_DemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DemoActionPerformed

		GUIController.Update(Actions.List.get((String) jComboBox_Action.getSelectedItem()).Action,
				jTextField_Target.getText(),
				jTextField_Replace.getText(),
				jTextField_FilePath.getText(),
				jCheckBox_isFolder.isSelected(),
				jCheckBox_isFiles.isSelected(),
				jCheckBox_SubFolders.isSelected());
		GUIController.batchRename.Prepair();
		new GUItabelList(GUIController.batchRename.getCFiles(), new CFile(), "test run").setVisible(true);

    }//GEN-LAST:event_jButton_DemoActionPerformed
    private void jButton_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RunActionPerformed

		GUIController.Update(Actions.List.get((String) jComboBox_Action.getSelectedItem()).Action,
				jTextField_Target.getText(),
				jTextField_Replace.getText(),
				jTextField_FilePath.getText(),
				jCheckBox_isFolder.isSelected(),
				jCheckBox_isFiles.isSelected(),
				jCheckBox_SubFolders.isSelected());
		GUIController.batchRename.Prepair();
		GUIController.batchRename.rename();
		new GUItabelList(GUIController.batchRename.getCFiles(), new CFile(), "Renamed").setVisible(true);

    }//GEN-LAST:event_jButton_RunActionPerformed
    private void jButton_UndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UndoActionPerformed

		GUIController.batchRename.undoRename();
		new GUItabelList(GUIController.batchRename.getCFiles(), new CFile(), "undo rename").setVisible(true);

    }//GEN-LAST:event_jButton_UndoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) throws IOException {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Demo;
    private javax.swing.JButton jButton_FilePath;
    private javax.swing.JButton jButton_Run;
    private javax.swing.JButton jButton_Undo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox_SubFolders;
    private javax.swing.JCheckBox jCheckBox_isFiles;
    private javax.swing.JCheckBox jCheckBox_isFolder;
    private javax.swing.JComboBox<String> jComboBox_Action;
    private javax.swing.JLabel jLabel_Action;
    private javax.swing.JLabel jLabel_FilePath;
    private javax.swing.JLabel jLabel_Replacement;
    private javax.swing.JLabel jLabel_Target;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_FilePath;
    private javax.swing.JTextField jTextField_Replace;
    private javax.swing.JTextField jTextField_Target;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
