package BatchFileRename;

import java.io.*;
import java.util.regex.*;
import javax.swing.*;

public class GUI extends javax.swing.JFrame {

	String colName[] = {"No", "Original Name", "New Name"};

	/**
	 * Creates new form GUII
	 */
	public GUI() {
		initComponents();
		//this.getContentPane().setBackground(Color.WHITE);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FileButton = new javax.swing.JButton();
        jButton_Run = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox_isRegex = new javax.swing.JCheckBox();
        jCheckBox_isFiles = new javax.swing.JCheckBox();
        jCheckBox_isFolder = new javax.swing.JCheckBox();
        jTextField_Target = new javax.swing.JTextField();
        jTextField_Replace = new javax.swing.JTextField();
        FilePath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.white);

        FileButton.setText("Load");
        FileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileButtonActionPerformed(evt);
            }
        });

        jButton_Run.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Run.setText("Run");
        jButton_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RunActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Target");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Replacement");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("File Path");

        jCheckBox_isRegex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_isRegex.setText("Is regex");
        jCheckBox_isRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_isRegexActionPerformed(evt);
            }
        });

        jCheckBox_isFiles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_isFiles.setSelected(true);
        jCheckBox_isFiles.setText("Files");
        jCheckBox_isFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_isFilesActionPerformed(evt);
            }
        });

        jCheckBox_isFolder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox_isFolder.setText("Folders");
        jCheckBox_isFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_isFolderActionPerformed(evt);
            }
        });

        jTextField_Target.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Replace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        FilePath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 496, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Run))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox_isRegex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox_isFolder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox_isFiles))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(FileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Target)
                            .addComponent(FilePath)
                            .addComponent(jTextField_Replace))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(FileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Target, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_isFiles)
                            .addComponent(jCheckBox_isFolder)
                            .addComponent(jCheckBox_isRegex)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_Replace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void FileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FileButtonActionPerformed
   {//GEN-HEADEREND:event_FileButtonActionPerformed

	   JFileChooser browse = new JFileChooser();

	   browse.setDialogTitle("Browse");
	   browse.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
	   browse.setAcceptAllFileFilterUsed(false);
	   browse.setRequestFocusEnabled(rootPaneCheckingEnabled);
	   browse.setCurrentDirectory(new File("."));

	   if (browse.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
		   if (browse.getSelectedFile().toString() == null) {
			   JOptionPane.showMessageDialog(null, "can't load the image", "Error", JOptionPane.ERROR_MESSAGE);
		   } else {
			   FilePath.setText(browse.getSelectedFile().toString());
		   }
	   }

   }//GEN-LAST:event_FileButtonActionPerformed

   private void jButton_RunActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_RunActionPerformed
   {//GEN-HEADEREND:event_jButton_RunActionPerformed

	   String Target = this.jTextField_Target.getText();
	   if (this.jCheckBox_isRegex.isSelected()) {
		   Target = Pattern.quote(Target);
	   }

	   String[][] cells = FileRenameing.Replace(this.FilePath.getText(), Target, this.jTextField_Replace.getText(), this.jCheckBox_isFiles.isSelected(), this.jCheckBox_isFolder.isSelected());
	   new GUItabelList(cells, this.colName, "Files").setVisible(true);

						   }//GEN-LAST:event_jButton_RunActionPerformed

    private void jCheckBox_isRegexActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBox_isRegexActionPerformed
    {//GEN-HEADEREND:event_jCheckBox_isRegexActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_isRegexActionPerformed

    private void jCheckBox_isFilesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBox_isFilesActionPerformed
    {//GEN-HEADEREND:event_jCheckBox_isFilesActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_isFilesActionPerformed

    private void jCheckBox_isFolderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBox_isFolderActionPerformed
    {//GEN-HEADEREND:event_jCheckBox_isFolderActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_isFolderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

		String Target = this.jTextField_Target.getText();
		if (this.jCheckBox_isRegex.isSelected()) {
			Target = Pattern.quote(Target);
		}

		String[][] cells = FileRenameing.Test(this.FilePath.getText(), Target, this.jTextField_Replace.getText(), this.jCheckBox_isFiles.isSelected(), this.jCheckBox_isFolder.isSelected());
		new GUItabelList(cells, this.colName, "Files").setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) throws IOException {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FileButton;
    private javax.swing.JTextField FilePath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Run;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox_isFiles;
    private javax.swing.JCheckBox jCheckBox_isFolder;
    private javax.swing.JCheckBox jCheckBox_isRegex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Replace;
    private javax.swing.JTextField jTextField_Target;
    // End of variables declaration//GEN-END:variables
}
